export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DESTROY_QUESTION = 'DESTROY_QUESTION';
